#!/bin/bash

javac cbcdec.java
v_exist=0
while getopts :k:i:o:v: option
	do
		case "$option" in
		k)
			keyfile="$OPTARG"
			;;
		i)
			infile="$OPTARG"
			;;
		o)	outfile="$OPTARG"
			;;
		v)  ivfile="$OPTARG"
			v_exist=1
			;;
			esac
	done
if [ "$v_exist" = "1" ]; then
	java cbcdec -k $keyfile -i $infile -o $outfile -v $ivfile
else
	java cbcdec -k $keyfile -i $infile -o $outfile
fi
