#!/bin/bash

javac cbcmac_tag.java
while getopts :k:m:t: option
	do
		case "$option" in
		k)
			keyfile="$OPTARG"
			;;
		m)
			infile="$OPTARG"
			;;
		t)	outfile="$OPTARG"
			;;
			esac
	done
	java cbcmac_tag -k $keyfile -m $infile -t $outfile
