#!/bin/bash

javac lock.java
while getopts :d:p:r:vk: option
	do
		case "$option" in
		d)
			directory="$OPTARG"
			;;
		p)
			pubkey="$OPTARG"
			;;
		r)	privkey="$OPTARG"
			;;
		vk)	vpk="$OPTARG"
			;;
			esac
	done
	java lock -d $directory -p $pubkey -r $privkey -vk $vpk
