#!/bin/bash

javac lock.java
javac rsa_sign.java
while getopts :d:p:r:v: option
	do
		case "$option" in
		d)
			directory="$OPTARG"
			;;
		p)
			pubkey="$OPTARG"
			;;
		r)	privkey="$OPTARG"
			;;
		v)	vpk="$OPTARG"
			;;
			esac
	done

#Lock creates an AES key, encrypts it with pubkey, and writes to symmetric key manifest
ca=$pubkey'-casig'
./rsa-validate \-k $vpk -m $pubkey -s $ca | grep 'False' && echo "Invalid public key" && exit 1
echo "Public Key validated by Signing Authority"
java lock $directory $pubkey
java rsa_sign \-k $privkey -m $directory'/manifest' \-s $directory'/manifest.sig'
