#!/bin/bash

javac unlock.java
while getopts :d:p:r: option
	do
		case "$option" in
		d)
			directory="$OPTARG"
			;;
		p)
			pubkey="$OPTARG"
			;;
		r)	privkey="$OPTARG"
			;;
			esac
	done

ca=$pubkey'-casig'
./rsa-validate \-k $8 \-m $pubkey \-s $ca | grep 'False' && echo "Invalid public key" && exit 1
echo "Public Key validated by Signing Authority"
./rsa-validate \-k $pubkey -m $directory'/manifest' \-s $directory'/manifest.sig' | grep 'False' && echo "Manifest Signature error" && exit 1
echo "Symmetric Key Manifest Integrity Verified"
java unlock $directory $pubkey $privkey
